# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: macandkaj/ci_test
    steps:
      - checkout
      - run:
          name: prepare
          command: cmake app;
      - run:
          name: build-app
          command: make app;
  test:
    docker:
      - image: macandkaj/ci_test
    steps:
      - checkout
      - run:
          name: prepare
          command: cmake app;
      - run:
          name: build-test
          command: make Test; 
      - run:
          name: run-test
          command: "./test/Test --gtest_output=xml:test-result/result.xml"
      - store_test_results:
          path: test-result

workflows:
  CI_Test-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
